# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["model.py"]

doc_url = "https://cbergroth.github.io/ml_project_template_test/"

git_url = "https://github.com/cbergroth/ml_project_template_test/tree/master/"

def custom_doc_links(name): return None
